Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -7,33 +7,64 @@ on:
     branches: [ "pipeline" ]
 
 jobs:
-
-  build:
-
+  checkout-code:
     runs-on: ubuntu-latest
-
     steps:
-    - name : Checkout code
-      uses: actions/checkout@v3
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-    - name : Set up Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: '3.x'
+  setup-python:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.x'
 
-    - name : Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install -r requirements.txt
+  install-dependencies:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-    - name : Run tests
-      run: |
-        coverage run --source=. -m pytest
+      - name: Install dependencies
+        run: pip install -r requirements.txt
 
-    - name: Build Docker image
-      uses: docker/build-push-action@v2
-      with:
-        context: .
-        push: true
-        tags: outil-de-visualisation-evolution-des-traces-execution:$(date +%s)
-        file: Dockerfile
+  run-tests:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Run tests with coverage
+        run: coverage run --source=. -m pytest
+
+  # check-coverage:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v2
+
+  #     - name: Check code coverage
+  #       run: |
+  #         # Get coverage percentage from the coverage report
+  #         COVERAGE_PERCENTAGE=$(coverage report --fail-under=80 | grep TOTAL | awk '{print $NF}')
+
+  #         # Check if coverage is above 80%
+  #         if [[ $COVERAGE_PERCENTAGE < 80 ]]; then
+  #           echo "Code coverage is below 80% ($COVERAGE_PERCENTAGE%)"
+  #           exit 1
+  #         fi
+
+  build-docker-image:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Build Docker image
+        uses: docker/build-push-action@v2
+        with:
+          context: .
+          push: true
+          tags: tommyti/outil-de-visualisation-evolution-des-traces-execution:latest
